# gemini_callback.ps1 - Assemble context and launch Gemini CLI for orchestrator review
# Run from project root. Builds logs/callback_context.md then invokes Gemini with callback prompt.

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
Set-Location $projectRoot

$contextPath = "logs/callback_context.md"
$nextPromptPath = "prompts/next_callback_prompt.md"
$defaultPromptPath = "prompts/gemini_callback_default.md"

# Gemini CLI: executable (default "gemini") and optional args (default "-y")
$geminiExe = if ($env:GEMINI_CLI_CMD) { $env:GEMINI_CLI_CMD } else { "gemini" }
$geminiArgs = @("-y")

# Ensure logs dir exists
$logsDir = "logs"
if (-not (Test-Path $logsDir)) { New-Item -ItemType Directory -Path $logsDir -Force | Out-Null }

# Ensure agent_status.json exists for workers
$statusPath = "logs/agent_status.json"
if (-not (Test-Path $statusPath)) {
    @{ completed = @(); last_updated = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"); callback_requested = $true } | ConvertTo-Json -Depth 10 | Set-Content $statusPath
} else {
    $status = Get-Content $statusPath -Raw | ConvertFrom-Json
    $status.callback_requested = $true
    $status.last_updated = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
    $status | ConvertTo-Json -Depth 10 | Set-Content $statusPath
}

# Build context bundle: paths and short summaries for Gemini
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# Callback context (generated by gemini_callback.ps1)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("A callback was requested. As the orchestrator, read the following files and perform the callback procedure.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Files to read")
[void]$sb.AppendLine("- tasks/queue.json")
[void]$sb.AppendLine("- logs/agent_status.json")
[void]$sb.AppendLine("- logs/agent_errors.json (if present)")
[void]$sb.AppendLine("- docs/TASKS.md")
[void]$sb.AppendLine("- docs/QUALITY_STANDARDS.md")
[void]$sb.AppendLine("- docs/LEGAL_COMPLIANCE.md")
[void]$sb.AppendLine("- logs/human_reviews.md (if present)")
[void]$sb.AppendLine("")

# List outputs/agent_deliverables
$outDir = "outputs/agent_deliverables"
if (Test-Path $outDir) {
    [void]$sb.AppendLine("## Deliverables in outputs/agent_deliverables/")
    Get-ChildItem -Path $outDir -Recurse -File | ForEach-Object {
        [void]$sb.AppendLine("- $($_.FullName.Replace($projectRoot, '').TrimStart('\','/'))")
    }
    [void]$sb.AppendLine("")
} else {
    [void]$sb.AppendLine("## Deliverables: (none - outputs/agent_deliverables/ missing or empty)")
    [void]$sb.AppendLine("")
}

# Optional: embed last N lines of agent_status for quick view
if (Test-Path $statusPath) {
    [void]$sb.AppendLine("## Agent status (preview)")
    [void]$sb.AppendLine("```")
    [void]$sb.AppendLine((Get-Content $statusPath -Raw))
    [void]$sb.AppendLine("```")
}

$contextPath | Set-Content $sb.ToString() -Encoding UTF8
Write-Host "Context written to $contextPath"

# Determine user prompt for Gemini
$userPrompt = $null
if (Test-Path $nextPromptPath) {
    $userPrompt = Get-Content $nextPromptPath -Raw
    Write-Host "Using prompt from $nextPromptPath"
} else {
    # Create and use default callback prompt if missing
    $defaultPrompt = @"
You are the orchestrator. A callback was requested.

1. Read the file: logs/callback_context.md (it lists all files you need).
2. Read tasks/queue.json, logs/agent_status.json, and any listed deliverables.
3. Review each completed task against docs/QUALITY_STANDARDS.md and docs/LEGAL_COMPLIANCE.md.
4. Refine or correct outputs as needed; flag items for human review.
5. Update docs/TASKS.md with progress.
6. Refill or reprioritize tasks/queue.json and backlog.
7. Write the next prompts/next_callback_prompt.md for the following run.
"@
    if (-not (Test-Path (Split-Path $defaultPromptPath))) {
        $promptsDir = "prompts"
        if (-not (Test-Path $promptsDir)) { New-Item -ItemType Directory -Path $promptsDir -Force | Out-Null }
    }
    $defaultPrompt | Set-Content $defaultPromptPath -Encoding UTF8
    $userPrompt = $defaultPrompt
    Write-Host "No next_callback_prompt.md found; using default and saving to $defaultPromptPath"
}

# Invoke Gemini CLI: pass prompt and context file path
# User can set GEMINI_CLI_CMD to their exact command. We pass one argument: instruction to read context + the prompt.
$fullInstruction = "Read the context in logs/callback_context.md. Then follow these instructions:`n`n$userPrompt"
$argFile = "logs/callback_prompt_arg.txt"
$fullInstruction | Set-Content $argFile -Encoding UTF8

Write-Host "Launching Gemini CLI: $geminiExe -y. Prompt piped from $argFile."
Get-Content $argFile -Raw | & $geminiExe @geminiArgs
if ($LASTEXITCODE -ne 0 -and $null -ne $LASTEXITCODE) {
    Write-Host "Gemini CLI exited with code $LASTEXITCODE. Run manually: Get-Content logs/callback_prompt_arg.txt | $geminiExe -y"
}
